### ISSUE TITLE
exception upon high mag cursor position change

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#113]
New : XF:17ID-ES:FMX{Misc-AuxCursor3:Y}Pos-SP.VAL 256
Traceback (most recent call last):
                                    File "_ctypes/callbacks.c", line 234, in 'calling callback function'
                                                                                                          File "/opt/conda_envs/lsdc-gui-2021-1.1/lib/python3.6/site-packages/epics/ca.py", line 711, in _onMonitorEvent
                                                            args.usr(value=value, **kwds)
                                                                                           File "/opt/conda_envs/lsdc-gui-2021-1.1/lib/python3.6/site-packages/epics/pv.py", line 766, in __on_changes
                                          self.run_callbacks()
                                                                File "/opt/conda_envs/lsdc-gui-2021-1.1/lib/python3.6/site-packages/epics/pv.py", line 47, in wrapped
         return func(self, *args, **kwargs)
                                             File "/opt/conda_envs/lsdc-gui-2021-1.1/lib/python3.6/site-packages/epics/pv.py", line 777, in run_callbacks
                                                                                                                                                         [jaishima@xf17id2-ioc1 save] FMX $     self.run_callback(index)
                                                          File "/opt/conda_envs/lsdc-gui-2021-1.1/lib/python3.6/site-packages/epics/pv.py", line 47, in wrapped
                                                                                                                                                                   return func(self, *args, **kwargs)
                                       File "/opt/conda_envs/lsdc-gui-2021-1.1/lib/python3.6/site-packages/epics/pv.py", line 800, in run_callback
                                                                                                                                                      fcn(**kwd)
                                                                                                                                                                 File "/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc/lsdcGui.py", line 5088, in processHighMagCursorChangeCB
                                                                                                                   self.highMagCursorChangeSignal.emit(posRBV,ID)
 TypeError: ControlMain.highMagCursorChangeSignal[str] signal has 1 argument(s) but 2 provided
                                                                                              caget XF:17ID-ES:FMX{Misc-AuxCursor3:Y}Pos-SP.VAL

**Comment by JunAishima** [comment]
The definition of the highMagCursorChangeSignal, lowMagCursorChangeSignal, and roiChangeSignal all should have two arguments in their definitions - however, the initial definition of the signals is only for one string.

**Comment by JunAishima** [comment]
fixed in e032d247add42a70e52a63ff1d10e38a2efa744e
