### ISSUE TITLE
NYX using GUI user screen governor state changes fail

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#174]
The call for governor state changes is incorrect in the LSDC GUI.

```
2022-01-14 13:17:43,739 daq_main_common INFO     executing command: setGovRobot('SE')
ERROR:daq_main_common:Type error. Error: setGovRobot() missing 1 required positional argument: 'state'
Traceback (most recent call last):
  File "/data/Software/LSDC/lsdc/daq_main_common.py", line 156, in process_input
    execute_command(command_string)
  File "/data/Software/LSDC/lsdc/daq_main_common.py", line 35, in execute_command
    exec(command_s)
  File "<string>", line 1, in <module>
TypeError: setGovRobot() missing 1 required positional argument: 'state'
2022-01-14 13:17:43,740 daq_main_common ERROR    Type error. Error: setGovRobot() missing 1 required positional argument: 'state'

```

**Comment by JunAishima** [comment]
after testing, this works as expected. closing!
