### ISSUE TITLE
Clicking Edit Raster Params button crashes GUI

### ISSUE THREAD

**Issue by dalekreitler-bnl** [NSLS-II/lsdc#20]
Clicking the edit raster params button in lsdc gui window results in GUI crashing, the following error shows up in the terminal from which GUI was launched (but not in gui log file):

Traceback (most recent call last):
  File "/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/lsdcGui.py", line 4211, in editScreenParamsCB
    self.screenDefaultsDialog = ScreenDefaultsDialog(self)
  File "/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/lsdcGui.py", line 707, in __init__
    self.exp_time_ledit.textChanged.connect(self.checkEntryState)
AttributeError: 'ScreenDefaultsDialog' object has no attribute 'checkEntryState'

This issue could possibly be related to NSLS-II/lsdc#18

Beamline staff also reports that under some circumstances (exactly which currently unknown) drawing/defining the raster grid causes GUI to crash before the grid is displayed.

**Comment by dalekreitler-bnl** [comment]
Edit raster params button opens window without crashing GUI now
