### ISSUE TITLE
NYX robot issue

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#225]
INFO:denso_robot:Mounting: A 8^M
2022-06-16 13:24:48,912 denso_robot INFO     Mounting: A 8
ERROR:denso_robot:Exception during mount step: Can't mount 8A: failed to mount: traceback: Traceback (most recent call last):^M
  File "/nsls2/software/mx/daq/lsdc_nyx/denso_robot.py", line 33, in mount^M
    yield from self.robot.mount(denso_puck_pos, denso_pin_pos)^M
  File "/opt/conda_envs/lsdc-server-2022-2.2/lib/python3.9/site-packages/nyxtools/robot.py", line 149, in mount^M
    raise RuntimeError(f"Can't mount {sample_str}: failed to mount")^M
RuntimeError: Can't mount 8A: failed to mount^M
^M
2022-06-16 13:25:20,445 denso_robot ERROR    Exception during mount step: Can't mount 8A: failed to mount: traceback: Traceback (most recent call last):
  File "/nsls2/software/mx/daq/lsdc_nyx/denso_robot.py", line 33, in mount
    yield from self.robot.mount(denso_puck_pos, denso_pin_pos)
  File "/opt/conda_envs/lsdc-server-2022-2.2/lib/python3.9/site-packages/nyxtools/robot.py", line 149, in mount
    raise RuntimeError(f"Can't mount {sample_str}: failed to mount")
RuntimeError: Can't mount 8A: failed to mount

INFO:bluesky.RE.state:Change state on <bluesky.run_engine.RunEngine object at 0x7fe81bb94b20> from 'running' -> 'idle'^M
2022-06-16 13:25:20,446 bluesky.RE.state INFO     Change state on <bluesky.run_engine.RunEngine object at 0x7fe81bb94b20> from 'running' -> 'idle'
INFO:bluesky:Cleaned up from plan <generator object DensoRobot.mount at 0x7fe810096890>^M
2022-06-16 13:25:20,446 bluesky  INFO     Cleaned up from plan <generator object DensoRobot.mount at 0x7fe810096890>
ERROR:denso_robot:Failure during mount/unmount. Spindle_occupied: expected: 1 actual: 0. Puck num: expected: 0 actual: 0 Sample num: expected 7 actual: 7^M
2022-06-16 13:25:20,453 denso_robot ERROR    Failure during mount/unmount. Spindle_occupied: expected: 1 actual: 0. Puck num: expected: 0 actual: 0 Sample num: expected 7 actual: 7

**Comment by JunAishima** [comment]
closing as they no longer use the old denso robot
