### ISSUE TITLE
Hanging snapshots

### ISSUE THREAD

**Issue by dalekreitler-bnl** [NSLS-II/lsdc#37]
* When users collect single snapshot images as datasets sometimes the Eiger does not get the trigger from the zebra.
* Previously observed this issue for small rasters, vectorGo PV did not initiate vector and Eiger never receives the trigger.
* "Fixed" with commit (https://github.com/NSLS-II/lsdc/commit/5cc19d04c80fef03edf159c5a3ba116437bcf443).
* The raster "fix" now raises a timeout error when snapshots hang up for the same reason, during vectorActiveWait() in dac_macros
* propose same solution as used for rasters
![snapshots](https://user-images.githubusercontent.com/61419915/104262033-bf653880-5454-11eb-9db3-574ccb8a8b54.png)

**Comment by dalekreitler-bnl** [comment]
# Example of exception raised during hangup

2021-01-08 12:22:30,635 daq_macros INFO     vector Go 1610126550.6359673
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_main2.py in <module>
     43 if (len(sys.argv)>1):
     44   if (sys.argv[1] == "gui"):
---> 45     main(mode="gui")
     46 else:
     47   main(mode="shell")

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_main2.py in main(mode)
     36   pybass_init()
     37   if (mode=="gui"):
---> 38     run_server()
     39   else:
     40     lsdcHome = os.environ["LSDCHOME"]

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_main_common.py in run_server()
    181   comm_pv.add_callback(comm_cb)
    182   immediate_comm_pv.add_callback(comm2_cb)
--> 183   process_commands(0.5)

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_main_common.py in process_commands(frequency)
    103       command = command_list.pop(0)
    104       logger.info('command: %s' % command)
--> 105       process_input(command)
    106 
    107 

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_main_common.py in process_input(command_string)
    151   try:
    152     daq_lib.set_field("program_state","Program Busy")
--> 153     execute_command(command_string)
    154   except NameError as e:
    155     error_string = "Unknown command in queue: %s Error: %s" % (command_string, e)

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_main_common.py in execute_command(command_s)
     31 def execute_command(command_s):
     32   logger.info('executing command: %s' % command_s)
---> 33   exec(command_s)
     34 
     35 

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_main_common.py in <module>

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_lib.py in runDCQueue()
    487     refreshGuiTree() #just tells the GUI to repopulate the tree from the DB
    488     logger.info("calling collect data " + str(time.time()))
--> 489     colStatus = collectData(currentRequest)
    490     logger.info("done collecting data")
    491     if (autoMounted and db_lib.queueDone(daq_utils.beamline)):

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_lib.py in collectData(currentRequest)
    707       logger.info("moving omega to start " + str(time.time()))
    708       beamline_lib.mvaDescriptor("omega",sweep_start)
--> 709       imagesAttempted = collect_detector_seq_hw(sweep_start,range_degrees,img_width,exposure_period,file_prefix,data_directory_name,file_number_start,currentRequest)
    710   try:
    711     if (logMe):

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_lib.py in collect_detector_seq_hw(sweep_start, range_degrees, image_width, exposure_period, fileprefix, data_directory_name, file_number, currentRequest, z_target, changeState)
    790     daq_macros.vectorSync()
    791     logger.info("zebraDaq " + str(time.time()))
--> 792     daq_macros.zebraDaq(angleStart,range_degrees,image_width,exposure_period,file_prefix_minus_directory,data_directory_name,file_number,3,changeState)
    793 #    daq_macros.zebraDaq(angleStart,range_degrees,image_width,exposure_period,file_prefix_minus_directory,data_directory_name,file_number,3,protocol=protocol)  #?protocol?
    794   elif (protocol == "vector"):

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_macros.py in zebraDaq(angle_start, scanWidth, imgWidth, exposurePeriodPerImage, filePrefix, data_directory_name, file_number_start, scanEncoder, changeState)
   3155   logger.info("vector Go " + str(time.time()))
   3156   setPvDesc("vectorGo",1)
-> 3157   vectorActiveWait()
   3158   vectorWait()
   3159   zebraWait()

/GPFS/CENTRAL/xf17id1/skinnerProjectsBackup/lsdc_amx/daq_macros.py in vectorActiveWait()
    594   while (getPvDesc("VectorActive")!=1):
    595     if time.time() - start_time > 3: #if we have waited long enough, just throw an exception
--> 596       raise TimeoutError()
    597     time.sleep(0.05)
    598 

TimeoutError: 

In [1]: Do you really want to exit ([y]/n)? 
Exception in thread selector:
Traceback (most recent call last):
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/site-packages/caproto/threading/client.py", line 295, in __call__
    if obj.received(bytes_recv, address) is ca.DISCONNECTED:
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/site-packages/caproto/threading/client.py", line 1348, in received
    self._process_command(c)
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/site-packages/caproto/threading/client.py", line 1432, in _process_command
    sub.process(command)
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/site-packages/caproto/threading/client.py", line 2151, in process
    super().process(command)
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/site-packages/caproto/threading/client.py", line 2046, in process
    callback, *args, **kwargs)
  File "/opt/conda_envs/lsdcServer_2020-1.0/lib/python3.7/concurrent/futures/thread.py", line 151, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown

**Comment by dalekreitler-bnl** [comment]
Snapshot settings for reproducing failure

![Screenshot from 2021-01-12 12:29:20](https://user-images.githubusercontent.com/61419915/104350230-eca3fc00-54d1-11eb-9c8a-7d358bc52a18.png)
